class PrismScoreModel {
  final int evalYear,
      overallScore,
      EScore,
      SScore,
      GScore,
      overallRank,
      Erank,
      Srank,
      Grank,
      indOverallRank,
      indERank,
      indSRank,
      indGRank,
      WOverallScore,
      WEScore,
      WSScore,
      WGScore,
      WOverallRank,
      WERank,
      WSRank,
      WGRank;

  PrismScoreModel.fromJson(Map<String, dynamic> json)
      : evalYear = json['eval_year'],
        overallScore = json['overall_score'],
        EScore = json['e_score'],
        SScore = json['s_score'],
        GScore = json['g_score'],
        overallRank = json['overall_rank'],
        Erank = json['e_rank'],
        Srank = json['s_rank'],
        Grank = json['g_rank'],
        indOverallRank = json['ind_overall_rank'],
        indERank = json['ind_e_rank'],
        indSRank = json['ind_s_rank'],
        indGRank = json['ind_g_rank'],
        WOverallScore = json['w_overall_score'],
        WEScore = json['w_e_score'],
        WSScore = json['w_s_score'],
        WGScore = json['w_g_score'],
        WOverallRank = json['w_overall_rank'],
        WERank = json['w_e_rank'],
        WSRank = json['w_s_rank'],
        WGRank = json['w_g_rank'];
}
