class PrismScoreModel {
  final int prismScoreId,
      evalYear,
      overallScore,
      EScore,
      SScore,
      GScore,
      overallRank,
      Erank,
      Srank,
      Grank,
      indOverallRank,
      indERank,
      indSRank,
      indGRank,
      WOverallScore,
      WEScore,
      WSScore,
      WGScore,
      WOverallRank,
      WERank,
      WSRank,
      WGRank,
      companyId,
      prismIndAvgId,
      kcgsScoreId,
      esglabScoreId;

  PrismScoreModel.fromJson(Map<String, dynamic> json)
      : prismScoreId = json['Prism_score_id'],
        evalYear = json['Eval_year'],
        overallScore = json['Overall_score'],
        EScore = json['E_score'],
        SScore = json['S_score'],
        GScore = json['G_score'],
        overallRank = json['Overall_rank'],
        Erank = json['E_rank'],
        Srank = json['S_rank'],
        Grank = json['G_rank'],
        indOverallRank = json['Ind_overall_rank'],
        indERank = json['Ind_e_rank'],
        indSRank = json['Ind_s_rank'],
        indGRank = json['Ind_g_rank'],
        WOverallScore = json['W_overall_score'],
        WEScore = json['W_e_score'],
        WSScore = json['W_s_score'],
        WGScore = json['W_g_score'],
        WOverallRank = json['W_overall_rank'],
        WERank = json['W_e_rank'],
        WSRank = json['W_s_rank'],
        WGRank = json['W_g_rank'],
        companyId = json['Company_id'],
        prismIndAvgId = json['Prism_ind_avg_id '],
        kcgsScoreId = json['Kcgs_score_id'],
        esglabScoreId = json['Esglab_score_id'];
}
